version: "3.8"
services:
  server:
    env_file: .prod.env
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: jhenderson19/james-fec-proxy
    ports:
      - 80:3000
    restart: unless-stopped